name: cmapss
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - joblib
  - openpyxl
  - pyarrow
  - streamlit
  - plotly
  - pip
  - pip:
      - google-genai==1.47.0
